name: Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
      - run: |
          curl -fL "https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip" > /tmp/vault.zip
          unzip /tmp/vault.zip -d /tmp
          sudo mv /tmp/vault /usr/local/bin/vault
          sudo chmod 0755 /usr/local/bin/vault
        env:
          VAULT_VERSION: 1.18.3
      - run: npm ci
      - run: npm test
